{{- if .Values.gateway.enable -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.class.name }}
  listeners:
  {{- toYaml .Values.gateway.listeners | nindent 2 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.namespace }}
spec:
  parentRefs:
  - name: {{ .Release.Name }}-gateway
  hostnames:
  {{- toYaml .Values.gateway.route.hostnames | nindent 2 }}
  rules:
  {{- toYaml .Values.gateway.route.rules | nindent 2 }}
{{- end}}